TRAIN:
  IMG_DIR: "./data/Set5/"
  DATA_DIR: "./data/dbs/"
  DB: "Set5_val.pkl"
  # DB: "Urban100_train.pkl"
  SCALE: 5
VAL:
  IMG_DIR: "./data/Set5/"
  DATA_DIR: "./data/dbs/"
  DB: "Set5_val.pkl"
  SCALE: 5
